### ISSUE TITLE
__dirname resolving incorrectly in Electron packaged app

### ISSUE THREAD

**Issue by nickkraakman** [jamie-sherriff/android-platform-tools#1]
Hi, thanks for this wonderful package!

I currently use it in an [Electron](https://electronjs.org/) app, but some strange behavior occurred when I packaged my app for distribution using [electron-builder](https://github.com/electron-userland/electron-builder). 

Electron builder packages the app in a so-called `asar` archive, which is a like a `tar` archive. However, when running your `downloadAndReturnToolPaths` it gave an error, because it tried to download the Android Platform Tools `zip` _into the `app.asar` archive_ (see [here](https://github.com/scholtzm/electron-asar-dirname-issue) for more info on this issue).

It turned out that the `__dirname` you use in your code resolves to the `app.asar` path, which is not writable. You can see this when logging `androidToolZipPath` in `index.js` for example. This issue only occurs when the app is packaged. In development mode, before packaging, it works fine, since then there is no `app.asar`.

The workaround now was to set `"asar": false` in `package.json`, but this means that my source code is openly accessible. Would be great if you are able to look into a possible solution. Maybe us a different function to retrieve the current directory. Thanks!

**Comment by jamie-sherriff** [comment]
@nickkraakman Thanks for the issue! I have been a bit slack with this package as it needs some general maintenance. I can take a look this weekend and see if I can solve your problem.

**Comment by jamie-sherriff** [comment]
@nickkraakman Sorry for the delay, have pushed a branch called dirname-fix if you could please give it a try.
Easiest to install via npm like ```npm install jamie-sherriff/android-platform-tools#dirname-fix```

**Comment by nickkraakman** [comment]
@jamie-sherriff thanks so much! Will test it out when I update the tool I am using it in.

**Comment by jamie-sherriff** [comment]
Closing as fixed in 2.0.0
