### ISSUE TITLE
Custom paths not working

### ISSUE THREAD

**Issue by protyposis** [jamie-sherriff/android-platform-tools#3]
Hi,

`downloadTools('custom-path')` is not working because the `toolDirName` is never considered when downloading or extracting the zip file, so it ends up in the default directory.

For this reason, `downloadAndReturnToolPaths('custom-path')` fails at this line

https://github.com/jamie-sherriff/android-platform-tools/blob/6ab63a60b3e73b096235e4d6f3c08c1b0e2a05eb/index.js#L86

because `downloadTools` does not return the actual target directory. From looking at the code, I assume that if this was fixed, the next check would still fail because you do not pass in the path to `helper.getToolPaths()`:

https://github.com/jamie-sherriff/android-platform-tools/blob/6ab63a60b3e73b096235e4d6f3c08c1b0e2a05eb/index.js#L90

**Comment by jamie-sherriff** [comment]
Thanks for reporting!, 
ill look into this.

**Comment by jamie-sherriff** [comment]
@protyposis  Would you prefer platform tools gets nested under the 'customPath' like
`
custompath
  ->platform-tools
    -> tool binaries
`

Or the tool binaries extracted directly into the custom path?
`
custompath
  -> tool binaries
`

**Comment by protyposis** [comment]
I'd prefer the latter, directly into custom path. It's the more flexible way that allows both of your options above. Thank you!

**Comment by jamie-sherriff** [comment]
@protyposis Have got a branch with the fixes if you would like to have a play, otherwise i will publish it in the next few days.

`npm install git://github.com/jamie-sherriff/android-platform-tools#custom-paths`

**Comment by protyposis** [comment]
Tested and working, thanks! :+1:

**Comment by jamie-sherriff** [comment]
@protyposis  Thanks for testing

**Comment by jamie-sherriff** [comment]
Released in 2.0.1
